[project]
name = "vector-llm-compressor"
version = "0.1.0"
description = "Pipeline for quantizing/compressing LLM's"
readme = "README.md"
requires-python = ">=3.12"
dependencies = [
    "llmcompressor>=0.6.0.1",
]
